// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BButton: typeof import('bootstrap-vue-3')['BButton']
    BButtonGroup: typeof import('bootstrap-vue-3')['BButtonGroup']
    BCard: typeof import('bootstrap-vue-3')['BCard']
    BCardBody: typeof import('bootstrap-vue-3')['BCardBody']
    BCardHeader: typeof import('bootstrap-vue-3')['BCardHeader']
    BCardText: typeof import('bootstrap-vue-3')['BCardText']
    BCol: typeof import('bootstrap-vue-3')['BCol']
    BCollapse: typeof import('bootstrap-vue-3')['BCollapse']
    BContainer: typeof import('bootstrap-vue-3')['BContainer']
    BDropdown: typeof import('bootstrap-vue-3')['BDropdown']
    BDropdownItem: typeof import('bootstrap-vue-3')['BDropdownItem']
    BFormGroup: typeof import('bootstrap-vue-3')['BFormGroup']
    BFormInput: typeof import('bootstrap-vue-3')['BFormInput']
    BFormSelect: typeof import('bootstrap-vue-3')['BFormSelect']
    BModal: typeof import('bootstrap-vue-3')['BModal']
    BRow: typeof import('bootstrap-vue-3')['BRow']
    BTab: typeof import('bootstrap-vue-3')['BTab']
    BTable: typeof import('bootstrap-vue-3')['BTable']
    BTabs: typeof import('bootstrap-vue-3')['BTabs']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    vBToggle: typeof import('bootstrap-vue-3')['VBToggle']
    vBTooltip: typeof import('bootstrap-vue-3')['VBTooltip']
  }
}
